Src/Litium.Accelerator.Mvc/Controllers/Deployment/DeploymentController.cs
using Litium.Accelerator.Deployments;
using Litium.Accelerator.ViewModels.Deployment;
using Litium.Common;
using Litium.ComponentModel;
using Litium.Foundation.Modules.CMS;
using Litium.Foundation.Modules.ECommerce;
using Litium.Globalization;
using Litium.Media;
using Litium.Products;
using Litium.Runtime.AutoMapper;
using Litium.Studio.Extenssions;
using Litium.Websites;
using System;
using System.Linq;
using System.Web.Mvc;
using Litium.Accelerator.Builders.Deployment;
using Litium.Studio.Plugins.Suggestions;
using System.Globalization;
using Microsoft.Extensions.Logging;
using Litium.Foundation;

namespace Litium.Accelerator.Mvc.Controllers.Deployment
{
    public class DeploymentController : Controller
    {
        private readonly DeploymentViewModelBuilder _deploymentViewModelBuilder;
        private readonly FolderService _folderService;
        private readonly ChannelService _channelService;
        private readonly AssortmentService _assortmentService;
        private readonly WebsiteService _websiteService;
        private readonly StructureInfoService _structureInfoService;
        private readonly IPackageService _packageService;
        private readonly IPackage _package;
        private readonly SettingService _settingService;
        private readonly DomainNameService _domainNameService;
        private readonly ISuggestionService _suggestionService;
        private readonly ILogger<DeploymentController> _logger;
        private readonly InventoryService _inventoryService;
        private readonly PriceListService _priceListService;
        private readonly CategoryService _categoryService;
        private readonly BaseProductService _baseProductService;
        private readonly VariantService _variantService;
        private readonly MarketService _marketService;

        public DeploymentController(
            DeploymentViewModelBuilder deploymentViewModelBuilder,
            FolderService folderService,
            ChannelService channelService,
            AssortmentService assortmentService,
            IPackageService packageService,
            IPackage package,
            WebsiteService websiteService,
            StructureInfoService structureInfoService,
            SettingService settingService,
            DomainNameService domainNameService,
            ISuggestionService suggestionService,
            ILogger<DeploymentController> logger,
            InventoryService inventoryService,
            PriceListService priceListService,
            CategoryService categoryService,
            BaseProductService baseProductService,
            VariantService variantService,
            MarketService marketService)
        {
            _deploymentViewModelBuilder = deploymentViewModelBuilder;
            _folderService = folderService;
            _channelService = channelService;
            _assortmentService = assortmentService;
            _packageService = packageService;
            _package = package;
            _websiteService = websiteService;
            _structureInfoService = structureInfoService;
            _settingService = settingService;
            _domainNameService = domainNameService;
            _suggestionService = suggestionService;
            _logger = logger;
            _inventoryService = inventoryService;
            _priceListService = priceListService;
            _categoryService = categoryService;
            _baseProductService = baseProductService;
            _variantService = variantService;
            _marketService = marketService;
        }

        [Route("litium/deployment", Name = "DeploymentView")]
        public ActionResult Index()
        {
            var model = _deploymentViewModelBuilder.Build(ShowExport());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportPackage(DeploymentViewModel.ImportViewModel importForm)
        {
            var model = _deploymentViewModelBuilder.Build(ShowExport());

            if (!ValidateImportForm(importForm))
            {
                return View(nameof(Index), model);
            }
            _package.Type = importForm.PackageName;
            var structureInfo = _package.GetStructureInfo();
            structureInfo.CreateExampleProducts = importForm.CreateExampleProducts;

            var packageInfo = _package.CreatePackageInfo(structureInfo, importForm.Name, importForm.DomainName);
            model.ShowImport = true;
            model.CanImport = true;

            Solution.Instance.SearchService.IndexJobConsumer.Stop();
            try
            {
                _packageService.Import(structureInfo, packageInfo);
                _structureInfoService.UpdatePropertyReferences(structureInfo, packageInfo);
                model.ImportMessage = "accelerator.deployment.import.success".AsAngularResourceString();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Package installation error.");
                model.ImportMessage = "accelerator.deployment.error".AsAngularResourceString();
                try
                {
                    foreach (var variant in structureInfo.ProductCatalog.Variants)
                    {
                        var newVariant = _variantService.Get(structureInfo.Id(variant.SystemId));
                        if (newVariant != null)
                        {
                            _variantService.Delete(newVariant);
                        }
                    }

                    foreach (var product in structureInfo.ProductCatalog.BaseProducts)
                    {
                        var newProduct = _baseProductService.Get(structureInfo.Id(product.SystemId));
                        if (newProduct != null)
                        {
                            _baseProductService.Delete(newProduct);
                        }
                    }

                    foreach (var category in structureInfo.ProductCatalog.Categories)
                    {
                        var newCategory = _categoryService.Get(structureInfo.Id(category.SystemId));
                        if (newCategory != null)
                        {
                            _categoryService.Delete(newCategory);
                        }
                    }

                    _channelService.Delete(packageInfo.Channel);
                    _marketService.Delete(packageInfo.Market);
                    _websiteService.Delete(packageInfo.Website);
                    _assortmentService.Delete(packageInfo.Assortment);
                    _folderService.Delete(packageInfo.Folder);
                    _inventoryService.Delete(packageInfo.Inventory);
                    _priceListService.Delete(packageInfo.PriceList);
                }
                catch (Exception ee)
                {
                    _logger.LogError(ee, "Package installation cleanup error.");
                }
            }
            finally
            {
                Solution.Instance.SearchService.IndexJobConsumer.Start();
            }
            return View(nameof(Index), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ExportPackage(DeploymentViewModel.ExportViewModel exportForm)
        {
            var model = _deploymentViewModelBuilder.Build(ShowExport());

            if (!Guid.TryParse(exportForm.ChannelSystemId, out var channelSystemId) ||
                !Guid.TryParse(exportForm.FolderSystemId, out var folderSystemId)) 
            {
                return View(nameof(Index), model);
            }

            var channel = _channelService.Get(channelSystemId);
            _package.Type = channel.Localizations.CurrentCulture.Name.Replace(" ", "");
            var website = _websiteService.Get(channel.WebsiteSystemId.GetValueOrDefault());

            var assortment = GetAssortment(channel);

            if (assortment == null)
            {
                return View(nameof(Index), model);
            }

            var deliveryMethodCarriers = ModuleECommerce.Instance.DeliveryMethods.GetAll().Select(x => x.GetAsCarrier()).ToList();
            var paymentMethodCarriers = ModuleECommerce.Instance.PaymentMethods.GetAll().Select(paymentMethod => paymentMethod.GetAsCarrier()).ToList();

            var structureInfo = _packageService.Export(new PackageInfo
            {
                Assortment = assortment,
                Folder = _folderService.Get(folderSystemId),
                Channel = channel,
                Website = website,
                DeliveryMethods = deliveryMethodCarriers,
                PaymentMethods = paymentMethodCarriers,
            });
            _package.PersistStructureInfo(structureInfo);

            model.ExportMessage = "accelerator.deployment.export.success".AsAngularResourceString();

            return View(nameof(Index), model);
        }

        private Assortment GetAssortment(Channel channel)
        {
            var marketModel = channel.MarketSystemId?.MapTo<Market>();
            if (marketModel?.AssortmentSystemId == null)
            {
                return null;
            }
            var assortment = _assortmentService.Get(marketModel.AssortmentSystemId.GetValueOrDefault());
            return assortment;
        }

        private bool ShowExport()
        {
            return ModuleCMS.Instance.ModuleLicense.CustomerName.IndexOf("Litium Product-Team licenses", StringComparison.OrdinalIgnoreCase) != -1
                && Request.Url.Host.StartsWith("content-");
        }

        private bool ValidateImportForm(DeploymentViewModel.ImportViewModel importForm)
        {
            var isValid = true;

            if (string.IsNullOrWhiteSpace(importForm.PackageName))
            {
                isValid = false;
            }

            if (string.IsNullOrWhiteSpace(importForm.Name))
            {

Src/Litium.Accelerator.Mvc/Views/Deployment/Index.cshtml
@using Litium.Studio.Extenssions
@using Litium.Studio.ContentFingerprint
@model Litium.Accelerator.ViewModels.Deployment.DeploymentViewModel

@{
    ViewContext.RouteData.DataTokens["BareLayout"] = true;

    var importHeader = "accelerator.deployment.import.header".AsAngularResourceString();
    var exportHeader = "accelerator.deployment.export.header".AsAngularResourceString();
    var createExampleProductsCheckbox = "accelerator.deployment.createexampleproducts.label".AsAngularResourceString();
    var importButton = "accelerator.deployment.import.button".AsAngularResourceString();
    var exportButton = "accelerator.deployment.export.button".AsAngularResourceString();
}

<link href="@FingerprintExtension.ContentFingerprint("~/Litium/App/Content/app.min.css", useQueryHash: true)" rel="stylesheet" type="text/css" />
<script>
    function CheckImportPackage() {
        document.getElementById("loading").style.display = "block";
        return true;
    }
</script>
<style scoped>
    body {
        padding: 0 15px;
        width: 100%;
    }

    input[type=checkbox].form__checkbox ~ label[for=form__checkbox]:before {
        content: "";
        background-color: #fff;
        text-align: center;
        line-height: .9rem;
        margin-right: .5rem;
        border: 1px solid #999;
        border-radius: .1rem;
        height: .9rem;
        width: .9rem;
        vertical-align: text-top;
        box-sizing: content-box;
        display: inline-block;
        visibility: visible;
        cursor: pointer;
    }

    input[type=checkbox].form__checkbox:checked ~ label[for=form__checkbox]:before {
        content: "\f00c";
        font-family: Font Awesome\ 5 Free;
        color: #fff;
        background-color: #1494F6;
        border: 1px solid #1494F6;
    }

    .simpleform label[for=form__checkbox] {
        margin: 0;
    }

    .loading-container {
        position: absolute;
        width: 100%;
        height: 100%;
        display: block;
        z-index: 2000;
        background: #ddd;
        opacity: 0.6;
        margin-left: -15px;
        margin-right: -15px;
    }

        .loading-container::before {
            content: '';
            box-sizing: border-box;
            position: absolute;
            top: 50%;
            left: 50%;
            width: 30px;
            height: 30px;
            margin-top: -15px;
            margin-left: -15px;
            border-radius: 50%;
            border: 3px solid #ccc;
            border-top-color: #333;
            animation: spinner .6s linear infinite;
            z-index: 1;
        }

    @@keyframes spinner {
        to {
            transform: rotate(360deg);
        }
    }
</style>
@if (!string.IsNullOrWhiteSpace(Model.ImportMessage))
{
    <div class="base__status">
        <div class="base__message base__message__success">
            <i class="fa fa-check-circle base__message__icon"></i><span>
                @Model.ImportMessage
            </span>
        </div>
    </div>
}
@if (!string.IsNullOrWhiteSpace(Model.ExportMessage))
{
    <div class="base__status">
        <div class="base__message base__message__success">
            <i class="fa fa-check-circle base__message__icon"></i><span>
                @Model.ExportMessage
            </span>
        </div>
    </div>
}
<div id="loading" class="loading-container" style="display: none">
</div>
<main class="layout row__col__xs__6 simpleform">
    <h1>@importHeader</h1>
    @if (Model.ShowImport)
    {
        using (Html.BeginForm("ImportPackage", "Deployment", FormMethod.Post, new { @onsubmit = "return CheckImportPackage()" }))
        {
            @Html.AntiForgeryToken()
            <p>
                @Html.LabelFor(x => x.ImportForm.Name, "accelerator.deployment.name.label".AsAngularResourceString()) <br />
                @Html.TextBoxFor(x => x.ImportForm.Name, new { @autocomplete = "on" })
                @Html.ValidationMessageFor(x => x.ImportForm.Name, string.Empty, new { @class = "base__color-error" }) <br />
            </p>
            <p>
                @Html.LabelFor(x => x.ImportForm.DomainName, "accelerator.deployment.domainname.label".AsAngularResourceString()) <br />
                @Html.TextBoxFor(x => x.ImportForm.DomainName, new { @autocomplete = "on" })
                @Html.ValidationMessageFor(x => x.ImportForm.DomainName, string.Empty, new { @class = "base__color-error" }) <br />
            </p>
            if (Model.Packages.Count == 1)
            {
                @Html.Hidden(Html.NameFor(x => x.ImportForm.PackageName).ToString(), Model.Packages[0].Value)
            }
            else if (Model.Packages.Count > 0)
            {
                <p>
                    @Html.LabelFor(x => x.ImportForm.PackageName, "accelerator.deployment.packagename.label".AsAngularResourceString()) <br />
                    @Html.DropDownListFor(x => x.ImportForm.PackageName, Model.Packages, new { @autocomplete = "on" }) <br />
                </p>
            }
            <p>
                @Html.LabelFor(x => x.ImportForm.CreateExampleProducts, "accelerator.deployment.exampleproducts.label".AsAngularResourceString()) <br />
                <label>
                    @Html.CheckBoxFor(x => x.ImportForm.CreateExampleProducts, new { @class = "form__checkbox" })
                    <label for="form__checkbox"></label>
                    @createExampleProductsCheckbox
                </label>
                <br />
            </p>
            <p>
                <button type="submit" class="base__success" @(Model.CanImport ? "" : $"disabled") onclick="var b = this; setTimeout(function () { b.disabled = true; }, 10)" ondblclick="return false;">@importButton</button>
            </p>
        }
    }
    else
    {
        <p>During beta the installation of a package can only be executed once.</p>
    }

    @if (Model.ShowExport)
    {
        <h1>@exportHeader</h1>
        using (Html.BeginForm("ExportPackage", "Deployment"))
        {
            @Html.AntiForgeryToken()
            <p>
                @Html.LabelFor(x => x.ExportForm.ChannelSystemId, "accelerator.deployment.channel.label".AsAngularResourceString()) <br />
                @Html.DropDownListFor(x => x.ExportForm.ChannelSystemId, Model.Channels, new { @autocomplete = "on" }) <br />
            </p>
            <p>
                @Html.LabelFor(x => x.ExportForm.FolderSystemId, "accelerator.deployment.folder.label".AsAngularResourceString()) <br />
                @Html.DropDownListFor(x => x.ExportForm.FolderSystemId, Model.Folders, new { @autocomplete = "on" }) <br />
            </p>
            <p>
                <button type="submit" class="base__success" @(Model.CanExport ? "" : $"disabled")>@exportButton</button>
            </p>
        }
    }

</main>