Src/Litium.Accelerator.Mvc/Controllers/Order/OrderController.cs
using System;
using System.Web.Mvc;
using Litium.Accelerator.Builders.Order;
using Litium.Accelerator.Services;
using Litium.Accelerator.StateTransitions;
using Litium.Web.Models.Websites;

namespace Litium.Accelerator.Mvc.Controllers.Order
{
    public class OrderController : ControllerBase
    {
        private readonly OrderHistoryViewModelBuilder _orderHistoryViewModelBuilder;
        private readonly OrderViewModelBuilder _orderViewModelBuilder;
        private readonly OrderHistoryViewModelService _orderHistoryViewModelService;
        private readonly OrderConfirmationViewModelBuilder _orderConfirmationViewModelBuilder;
        private readonly CartService _cartService;

        private readonly string BusinessCustomerOrderView = "BusinessCustomerOrder";
        private readonly string OrderConfirmationEmailView = "../Mail/ConfirmationEmail";

        public OrderController(OrderHistoryViewModelBuilder orderHistoryViewModelBuilder, 
            OrderViewModelBuilder orderViewModelBuilder, 
            OrderHistoryViewModelService orderHistoryViewModelService,
            CartService cartService,
            OrderConfirmationViewModelBuilder orderConfirmationViewModelBuilder)
        {
            _orderHistoryViewModelBuilder = orderHistoryViewModelBuilder;
            _orderViewModelBuilder = orderViewModelBuilder;
            _orderHistoryViewModelService = orderHistoryViewModelService;
            _orderConfirmationViewModelBuilder = orderConfirmationViewModelBuilder;
            _cartService = cartService;
        }

        [HttpGet]
        public ActionResult List(int page = 1, bool showMyOrders = false)
        {
            var model = _orderHistoryViewModelBuilder.Build(page, showMyOrders);
            return View(model);
        }

        [HttpGet]
        public ActionResult Order(string id, bool print = false)
        {
            var model = _orderViewModelBuilder.Build(id, print);
            if (model.IsBusinessCustomer)
            {
                return View(BusinessCustomerOrderView, model);
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Confirmation(PageModel currentPageModel, Guid? orderId, bool isEmail = false)
        {
            if (isEmail)
            {
                if (orderId.HasValue && orderId.Value != Guid.Empty)
                {
                    // In case of sending the order confirmation email, we get the orderId from the query string
                    var model = _orderConfirmationViewModelBuilder.Build(currentPageModel, orderId.Value);
                    return View(OrderConfirmationEmailView, model);
                }
                else
                {
                    this.Log().Error("An error occured while trying to render order confirmation email");
                    return View(OrderConfirmationEmailView);
                }
            }
            else
            {
                // In case of loading the order confirmation page, we get the orderId from the order carrier
                var model = _orderConfirmationViewModelBuilder.Build(currentPageModel);
                _cartService.Clear();
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApproveOrder(string id, bool isOrderPage = false, int page = 1, bool showMyOrders = false)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                _orderHistoryViewModelService.SaveOrder(OrderState.Confirmed, id);
            }

            if (isOrderPage)
            {
                return RedirectToAction(nameof(Order), new { Id = id});
            }

            if (showMyOrders)
            {
                return RedirectToAction(nameof(List), new { page, showMyOrders });
            }
            else
            {
                return RedirectToAction(nameof(List), new { page });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CancelOrder(string id, bool isOrderPage = false, int page = 1, bool showMyOrders = false)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                _orderHistoryViewModelService.SaveOrder(OrderState.Cancelled, id);
            }

            if (isOrderPage)
            {
                return RedirectToAction(nameof(Order), new { Id = id });
            }

            if (showMyOrders)
            {
                return RedirectToAction(nameof(List), new { page, showMyOrders });
            }
            else
            {
                return RedirectToAction(nameof(List), new { page });
            }
        }
    }
}

Src/Litium.Accelerator.Mvc/Views/Order/BusinessCustomerOrder.cshtml
@model Litium.Accelerator.ViewModels.Order.OrderViewModel
@using Litium.Accelerator.StateTransitions

@{
    ViewContext.RouteData.DataTokens["BareLayout"] = true;
}

<div class="row order-detail__container">
    <div class="columns">
        @if (Model.ShowButton)
        {
            <div class="row-inner order-detail__button-container">
                <div>
                    <a class="order-detail__button" href="@($"{Request?.Url?.AbsoluteUri}&print=true")" target="_blank">
                        @Html.WebSiteString("general.print")
                    </a>
                </div>
                @if (Model.Order.OrderStatus == (short)OrderState.WaitingConfirmation && Model.HasApproverRole)
                {
                    <div>
                        @using (Html.BeginForm("ApproveOrder", "Order", new { Id = Model.Order.ExternalOrderID, IsOrderPage = true }))
                        {
                            @Html.AntiForgeryToken()
                            <input class="order-detail__button" type="submit" value="@Html.WebSiteString("general.approve")" />
                        }
                    </div>
                    <div>
                        @using (Html.BeginForm("CancelOrder", "Order", new { Id = Model.Order.ExternalOrderID, IsOrderPage = true }))
                        {
                            @Html.AntiForgeryToken()
                            <input class="order-detail__button"type="submit" value="@Html.WebSiteString("general.cancel")" />
                        }
                    </div>
                }
                <div>
                    <input class="order-detail__button" type="button" value="@Html.WebSiteString("general.reorder")" onclick="parent.window.__litium.events.onReorderClick('@Model.Order.OrderId')" />
                </div>
                <div>
                    <a class="order-detail__button" href="@Model.OrderHistoryUrl">
                        @Html.WebSiteString("orderdetail.backtoorderlist")
                    </a>
                </div>
            </div>
        }
        <div class="row-inner">
            <div class="medium-6">
                <h3>
                    @Html.WebSiteString("orderdetail.ordernumber"): @Model.Order.ExternalOrderID
                </h3>
            </div>
            <div class="medium-6 text--right">
                <p>
                    <span>
                        @Html.WebSiteString("orderdetail.orderdate"): @Model.Order.OrderDate.ToString("d")
                    </span>
                    <br />
                    <span>
                        @Html.WebSiteString("orderdetail.orderstatus"): <strong> @Model.Order.Status</strong>
                    </span>
                    <br />
                    @if (Model.Order.ActualDeliveryDate.HasValue && Model.Order.ActualDeliveryDate.Value < DateTime.MaxValue.Date)
                    {
                        <span>
                            @Html.WebSiteString("orderdetail.deliverydate"): <strong>@(Model.Order.ActualDeliveryDate?.ToShortDateString())</strong>
                        </span>
                    }
                </p>
            </div>
        </div>
        <div class="row-inner">
            <div class="small-12">
                <div class="row medium-unstack no-margin">
                    <div class="medium-12">
                        @Html.WebSiteString("orderdetail.information")
                    </div>
                </div>
                <div class="row no-margin">
                    <div class="medium-12">
                        <p>
                            @Model.Order.CustomerInfo.Address1 <br />
                            @Model.Order.CustomerInfo.Zip @Model.Order.CustomerInfo.City
                            @Model.Order.CustomerInfo.Country
                        </p>
                        <p>
                            @Html.WebSiteString("orderdetail.organizationnumber"): @Model.Order.MerchantOrganizationNumber <br />
                            @Html.WebSiteString("orderdetail.orderreference"): @Model.Order.CustomerInfo.FirstName @Model.Order.CustomerInfo.LastName
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row-inner order-table">
            <div class="row medium-unstack no-margin order-table__header">
                <div class="columns medium-5">@Html.WebSiteString("orderdetail.column.products")</div>
                <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.quantity")</div>
                <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.price")</div>
                <div class="columns medium-3 text--right">@Html.WebSiteString("orderdetail.column.total")</div>
            </div>    
            <div class="order-table__body">
                @foreach (var delivery in Model.Order.Deliveries)
                {
                    foreach (var row in Model.Order.OrderRows.Where(x => x.DeliveryId == delivery.DeliveryId))
                    {
                        <div class="row medium-unstack no-margin">
                            <div class="columns medium-5">
                                <a href="@(row.Link?.Href)" target="_parent" class="order-detail__product-link">
                                    @row.Brand <strong>@row.Name</strong>
                                </a>
                            </div>
                            <div class="columns medium-2">
                                @row.QuantityString
                            </div>
                            <div class="columns medium-2">
                                @if (row.PriceInfo?.HasPrice == true)
                                {
                                    if (row.PriceInfo.CampaignPrice != null)
                                    {
                                        @row.PriceInfo.CampaignPrice.FormatPrice(true)
                                    }
                                    else
                                    {
                                        @row.PriceInfo.Price.FormatPrice(true)
                                    }
                                }
                            </div>
                            <div class="columns medium-3 text--right">
                                @row.TotalPrice
                            </div>
                        </div>
                    }
                    <div class="row medium-unstack no-margin">
                        <div class="columns medium-9">
                            @Html.WebSiteString("orderdetail.deliverymethod"): @delivery.DeliveryMethodTitle
                        </div>
                        <div class="columns medium-3 text--right">@delivery.DeliveryRowTotalCost</div>
                    </div>
                }
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-9">
                        @Html.WebSiteString("orderdetail.paymentmethod") - @Model.Order.PaymentMethod
                    </div>
                    <div class="columns medium-3 text--right">
                        @Model.Order.OrderTotalFee
                    </div>
                </div>
                @if (!string.IsNullOrEmpty(Model.Order.OrderTotalDiscountAmount))
                {
                    <div class="row medium-unstack no-margin">
                        <div class="columns medium-9">
                            @Html.WebSiteString("orderdetail.discount")
                        </div>
                        <div class="columns medium-3 text--right">
                            @Model.Order.OrderTotalDiscountAmount
                        </div>
                    </div>
                }
                <div class="row medium-unstack no-margin order-table__space-delimiter"></div>
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-3 medium-offset-9 text--right">
                        @Html.WebSiteString("orderdetail.grandtotal"): &nbsp &nbsp<strong>@Model.Order.OrderGrandTotal</strong>
                    </div>
                </div>
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-3 medium-offset-9 text--right">
                        @Html.WebSiteString("orderdetail.ordertotalvat"):  @Model.Order.OrderTotalVat
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    if (Model.IsPrintPage)
    {
        <script type="text/javascript">
            window.print();
        </script>
    }
}

Src/Litium.Accelerator.Mvc/Views/Order/Confirmation.cshtml
@model Litium.Accelerator.ViewModels.Order.OrderConfirmationViewModel

<div class="row">
    <div class="small-12 columns">
        <div class="simple-table order-summary">
            <div class="row medium-unstack no-margin simple-table__header">
                <div class="columns small-12 medium-6">
                    <h2>@Model.Title</h2>
                </div>
                <div class="columns small-12 medium-6 text--right">
                    <h2>@Html.WebSiteString("orderdetail.ordernumber"): @Model.Order.ExternalOrderID</h2>
                </div>
            </div>
            <div class="row medium-unstack no-margin simple-table__header">
                <div class="columns small-12 medium-6">
                    <h3>@Html.WebSiteString("orderdetail.deliveryaddress")</h3>
                </div> 
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="columns small-12 medium-6 text--right">
                        <h3>@Html.WebSiteString("orderdetail.customernumber"): @Model.Order.CustomerInfo.CustomerNumber</h3>
                    </div>
                }
            </div>
            <div class="row small-unstack no-margin">
            @foreach (var delivery in Model.Order.Deliveries)
            {
                <div class="columns small-12">
                    @{
                        if (string.IsNullOrEmpty(Model.Order.CompanyName))
                        {
                            @delivery.Address.FirstName
                            @delivery.Address.LastName
                        }
                        else
                        {
                            @Model.Order.CompanyName
                        }
                    }
                </div>
                <div class="columns small-12">
                    @delivery.Address.Address1
                </div>
                <div class="columns small-12">
                    @delivery.Address.Zip @delivery.Address.City
                </div>
                <div class="columns small-12">
                    @delivery.Address.Country
                </div>
            }
            </div>
        </div>

        @Html.Partial("_OrderSummary", Model.Order)

        <div class="simple-table order-summary">
            <div class="row medium-unstack no-margin simple-table__header">
                <div class="columns small-12 medium-6">
                    @Html.WebSiteString("orderdetail.information")
                </div>
            </div>
            <div class="row small-unstack no-margin">
                <div class="columns small-12">
                    @Model.Text
                </div>
            </div>
        </div>
    </div>
</div>

Src/Litium.Accelerator.Mvc/Views/Order/List.cshtml
@model Litium.Accelerator.ViewModels.Order.OrderHistoryViewModel
@using Litium.Accelerator.StateTransitions
@using Litium.Studio.Extenssions;

@{
    ViewContext.RouteData.DataTokens["BareLayout"] = true;
}

<div>
    @if (Model.IsBusinessCustomer && Model.HasApproverRole)
    {
        <div class="order__checkbox-container">
            <a href="@Model.MyOrdersLink" class="form__control columns">
                @Html.CheckBoxFor(x => x.ShowOnlyMyOrders, new { @checked = (Model.ShowOnlyMyOrders ? "checked" : string.Empty), @class="form__radio form--no-event" })
                @Html.WebSiteString("orderlist.showonlymyorders")
            </a>
        </div>
    }
    @if (Model.Orders != null && Model.Orders.Any())
    {
        <div class="simple-table">
            <div class="row medium-unstack no-margin simple-table__header">
                <div class="columns medium-2">@Html.WebSiteString("orderlist.column.orderdate")</div>
                <div class="columns medium-6">@Html.WebSiteString("orderlist.column.content")</div>
                <div class="columns medium-2">@Html.WebSiteString("orderlist.column.grandtotal")</div>
                <div class="columns medium-2">@Html.WebSiteString("orderlist.column.status")</div>
                @if (Model.IsBusinessCustomer)
                {
                    <div class="columns medium-2 hide-for-small-only"></div>
                }
            </div>
            @foreach (var order in Model.Orders)
            {
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-2">
                        @order.OrderDate.ToString("d")
                    </div>
                    <div class="columns medium-6">
                        @{
                        var orderRow = order.OrderRows.FirstOrDefault();
                        }
                        @if (orderRow != null)
                        {
                            <a href="@Model.OrderLink.Href?id=@order.ExternalOrderID" class="order-detail__product-link">
                                @orderRow.Brand
                                <b>
                                    @orderRow.Name
                                </b>
                                @if (order.OrderRows.Count > 1)
                                {
                                var count = order.OrderRows.Count - 1;
                                var formatText = (count == 1 ? "orderlist.item" : "orderlist.items").AsWebSiteString();
                                var orderText = string.Format(formatText, count);
                                @Html.Raw(orderText)
                                }
                            </a>
                        }
                    </div>
                    <div class="columns medium-2">
                        @order.OrderGrandTotal
                    </div>
                    <div class="columns medium-2">
                        @order.Status
                    </div>
                    @if (Model.IsBusinessCustomer)
                    {
                        <div class="columns medium-2">
                            @if (order.OrderStatus == (short)OrderState.WaitingConfirmation && Model.HasApproverRole)
                            {
                                using (Html.BeginForm("ApproveOrder", "Order", new { Id = order.ExternalOrderID, Page = Model.Pagination.CurrentPageIndex, ShowMyOrders = Model.ShowOnlyMyOrders }, FormMethod.Post, new { @class = "form--inline-block" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="table__icon table__icon--accept" title='@Html.WebSiteString("general.approve")'></button>
                                }

                                using (Html.BeginForm("CancelOrder", "Order", new { Id = order.ExternalOrderID, Page = Model.Pagination.CurrentPageIndex, ShowMyOrders = Model.ShowOnlyMyOrders }, FormMethod.Post, new { @class = "form--inline-block" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="table__icon table__icon--cancel" title='@Html.WebSiteString("general.cancel")'></button>
                                }
                            }
                            <button type="submit" class="table__icon table__icon--reorder" title='@Html.WebSiteString("general.reorder")' onclick="parent.window.__litium.events.onReorderClick('@order.OrderId')"></button>
                        </div>
                    }
                </div>
            }
        </div>

        @Html.DisplayFor(x => x.Pagination)
    }
    else
    {
        <div>@Html.WebSiteString("orderlist.noorderfound")</div>
    }
</div>

Src/Litium.Accelerator.Mvc/Views/Order/Order.cshtml
@model Litium.Accelerator.ViewModels.Order.OrderViewModel

@{
    ViewContext.RouteData.DataTokens["BareLayout"] = true;
}

<div class="row order-detail__container">
    <div class="columns">
        @if (Model.ShowButton)
        {
            <div class="row-inner order-detail__button-container">
                <div class="small-6">
                    <a class="order-detail__button" href="@($"{Request?.Url?.AbsoluteUri}&print=true")" target="_blank">
                        @Html.WebSiteString("general.print")
                    </a>
                </div>
                <div class="small-6 text--right">
                    <a class="order-detail__button" href="@Model.OrderHistoryUrl">
                        @Html.WebSiteString("orderdetail.backtoorderlist")
                    </a>
                </div>
            </div>
        }
        <div class="row-inner">
            <div class="medium-6">
                <h3>
                    @Html.WebSiteString("orderdetail.ordernumber"): @Model.Order.ExternalOrderID
                </h3>
            </div>
            <div class="medium-6 text--right">
                <p>
                    @Html.WebSiteString("orderdetail.orderdate"): @Model.Order.OrderDate.ToString("d") <br />
                    @Html.WebSiteString("orderdetail.orderstatus"): <strong> @Model.Order.Status</strong>
                </p>
            </div>
        </div>

        @if (Model.Order.ActualDeliveryDate.HasValue && Model.Order.ActualDeliveryDate.Value < DateTime.MaxValue.Date)
        {
            <div class="row-inner">
                <div class="medium-6 medium-offset-6 text--right">
                    @Html.WebSiteString("orderdetail.deliverydate"): <strong>@(Model.Order.ActualDeliveryDate?.ToShortDateString())</strong>
                </div>
            </div>
        }

        <div class="row-inner order-table">
            <div class="small-12">
                <div class="row medium-unstack no-margin order-table__header">
                    <div class="medium-12 columns">
                        @Html.WebSiteString("orderdetail.information")
                    </div>
                </div>
                @foreach (var delivery in Model.Order.Deliveries)
                {
                    <div class="row no-margin order-table__body">
                        <div class="medium-12 columns">
                            <p>
                                @delivery.Address.FirstName @delivery.Address.LastName <br />
                                @delivery.Address.Address1 <br />
                                @delivery.Address.Zip @delivery.Address.City <br />
                                @delivery.Address.Country
                            </p>

                        </div>
                    </div>
                }
            </div>
        </div>

            <div class="row-inner order-table">
                <div class="row medium-unstack no-margin order-table__header">
                    <div class="columns medium-5">@Html.WebSiteString("orderdetail.column.products")</div>
                    <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.quantity")</div>
                    <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.price")</div>
                    <div class="columns medium-3 text--right">@Html.WebSiteString("orderdetail.column.total")</div>
                </div>
                <div class="order-table__body">
                    @foreach (var row in Model.Order.OrderRows)
                    {
                        <div class="row medium-unstack no-margin">
                            <div class="columns medium-5">
                                <a href="@(row.Link?.Href)" target="_parent" class="order-detail__product-link">
                                    @row.Brand <strong>@row.Name</strong>
                                </a>
                            </div>
                            <div class="columns medium-2">
                                @row.QuantityString
                            </div>
                            <div class="columns medium-2">
                                @if (row.PriceInfo?.HasPrice == true)
                                {
                                    if (row.PriceInfo.CampaignPrice != null)
                                    {
                                        @row.PriceInfo.CampaignPrice.FormatPrice(true)
                                    }
                                    else
                                    {
                                        @row.PriceInfo.Price.FormatPrice(true)
                                    }
                                }
                            </div>
                            <div class="columns medium-3 text--right">
                                @row.TotalPrice
                            </div>
                        </div>
                    }

                <div class="row medium-unstack no-margin">
                    <div class="columns medium-9">
                        @Html.WebSiteString("orderdetail.paymentmethod") - @Model.Order.PaymentMethod
                    </div>
                    <div class="columns medium-3 text--right">
                        @Model.Order.OrderTotalFee
                    </div>
                </div>
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-9">
                        @Html.WebSiteString("orderdetail.deliverymethod") - @Model.Order.DeliveryMethod
                    </div>
                    <div class="columns medium-3 text--right">
                        @Model.Order.OrderTotalDeliveryCost
                    </div>
                </div>
                @if (!string.IsNullOrEmpty(Model.Order.OrderTotalDiscountAmount))
                {
                    <div class="row medium-unstack no-margin">
                        <div class="columns medium-9">
                            @Html.WebSiteString("orderdetail.discount")
                        </div>
                        <div class="columns medium-3 text--right">
                            @Model.Order.OrderTotalDiscountAmount
                        </div>
                    </div>
                }
                <div class="row medium-unstack no-margin order-table__space-delimiter"></div>
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-3 medium-offset-9 text--right">
                        @Html.WebSiteString("orderdetail.grandtotal"): &nbsp &nbsp<strong>@Model.Order.OrderGrandTotal</strong>
                    </div>
                </div>
                <div class="row medium-unstack no-margin">
                    <div class="columns medium-3 medium-offset-9 text--right">
                        @Html.WebSiteString("orderdetail.ordertotalvat"):  @Model.Order.OrderTotalVat
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model.IsPrintPage)
{
    <script type="text/javascript">
        window.print();
    </script>
}

Src/Litium.Accelerator.Mvc/Views/Order/_OrderSummary.cshtml
@model Litium.Accelerator.ViewModels.Order.OrderDetailsViewModel

<div class="simple-table order-summary">
    <div class="row medium-unstack no-margin simple-table__header">
        <div class="columns medium-6">@Html.WebSiteString("orderdetail.column.products")</div>
        <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.quantity")</div>
        <div class="columns medium-2">@Html.WebSiteString("orderdetail.column.price")</div>
        <div class="columns medium-2 text--right">@Html.WebSiteString("orderdetail.column.total")</div>
    </div>
    @foreach (var row in Model.OrderRows)
    {   var price="";
        if (row.PriceInfo?.HasPrice == true)
        {
            if (row.PriceInfo.CampaignPrice != null)
            {
                price = row.PriceInfo.CampaignPrice.FormatPrice(true);
            }
            else
            {
                price = row.PriceInfo.Price.FormatPrice(true);
            }
        }
        <div class="row medium-unstack no-margin">
            <div class="columns medium-6 small-6"><a href="@(row.Link?.Href)" class="order-detail__product-link">@row.Brand <strong>@row.Name</strong></a></div>
            <div class="columns medium-2 small-3">@row.QuantityString</div>
            <div class="columns medium-2 small-3">@price</div>
            <div class="columns medium-2 small-12 text--right">@row.TotalPrice</div>
        </div>
    }

    <div class="row medium-unstack no-margin">
        <div class="columns medium-10 ">@Html.WebSiteString("orderdetail.paymentmethod") - @Model.PaymentMethod</div>
        <div class="columns medium-2 text--right">@Model.OrderTotalFee</div>
    </div>

    <div class="row medium-unstack no-margin">
        <div class="columns medium-10 ">@Html.WebSiteString("orderdetail.deliverymethod") - @Model.DeliveryMethod</div>
        <div class="columns medium-2 text--right">@Model.OrderTotalDeliveryCost</div>
    </div>
    @if (!string.IsNullOrEmpty(Model.OrderTotalDiscountAmount))
    {
        <div class="row medium-unstack no-margin">
            <div class="columns medium-10 ">@Html.WebSiteString("orderdetail.discount")</div>
            <div class="columns medium-2 text--right">@Model.OrderTotalDiscountAmount</div>
        </div>
    }
    <div class="row medium-unstack no-margin order-summary__separator">
        <div class="columns medium-10 text--right"><h3>@Html.WebSiteString("orderdetail.grandtotal"):</h3></div>
        <div class="columns medium-2 text--right"><h3>@Model.OrderGrandTotal</h3></div>
    </div>

    <div class="row medium-unstack no-margin">
        <div class="columns medium-10 text--right"><h4>@Html.WebSiteString("orderdetail.ordertotalvat"):</h4></div>
        <div class="columns medium-2 text--right"><h4>@Model.OrderTotalVat</h4></div>
    </div>
</div>