Src/Litium.Accelerator.Mvc/Controllers/Login/LoginController.cs
using Litium.Accelerator.Mvc.ModelStates;
using Litium.Accelerator.Services;
using Litium.Accelerator.Utilities;
using Litium.Accelerator.ViewModels.Login;
using Litium.Customers;
using Litium.Foundation.Security;
using Litium.Studio.Extenssions;
using System.Web.Mvc;
using Litium.Accelerator.Builders.Login;
using ModelState = Litium.Accelerator.Services.ModelState;
using System;
using Litium.Web.Administration.WebApi.Common;
using Litium.Web.Routing;

namespace Litium.Accelerator.Mvc.Controllers.Login
{
    public class LoginController : ControllerBase
    {
        private readonly LoginService _loginService;
        private readonly MyPagesViewModelService _myPagesViewModelService;
        private readonly SecurityToken _securityToken;
        private readonly LoginViewModelBuilder _loginViewModelBuilder;
        private readonly ForgotPasswordViewModelBuilder _forgotPasswordViewModelBuilder;
        private readonly OrganizationService _organizationService;
        private readonly RouteRequestLookupInfoAccessor _routeRequestLookupInfoAccessor;

        private readonly ModelState _modelState;
        public LoginController(LoginService loginService, SecurityToken securityToken, LoginViewModelBuilder loginViewModelBuilder, 
            ForgotPasswordViewModelBuilder forgotPasswordViewModelBuilder, OrganizationService organizationService,
            MyPagesViewModelService myPagesViewModelService, RouteRequestLookupInfoAccessor routeRequestLookupInfoAccessor)
        {
            _loginService = loginService;
            _securityToken = securityToken;
            _loginViewModelBuilder = loginViewModelBuilder;
            _forgotPasswordViewModelBuilder = forgotPasswordViewModelBuilder;
            _organizationService = organizationService;
            _myPagesViewModelService = myPagesViewModelService;
            _modelState = new MvcModelState(ModelState);
            _routeRequestLookupInfoAccessor = routeRequestLookupInfoAccessor;
        }

        [HttpGet]
        public virtual ActionResult Login(string redirectUrl)
        {
            var model = _loginViewModelBuilder.Build(redirectUrl ?? string.Empty);
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Login(LoginViewModel loginViewModel)
        {
            var model = _loginViewModelBuilder.Build(loginViewModel);
            model.RedirectUrl = loginViewModel.RedirectUrl;

            if (!_loginService.IsValidLoginForm(_modelState, model.LoginForm))
            {
                return View(model);
            }

            try
            {
                var loginSuccessfull = _loginService.Login(model.LoginForm.UserName, model.LoginForm.Password, out var token);
                if (loginSuccessfull)
                {
                    var person = _loginService.GetUser(model.LoginForm.UserName);

                    if (!_loginService.IsBusinessCustomer(person, out var organizations))
                    {
                        return new RedirectResult(model.RedirectUrl);
                    }
                    if (organizations.Count <= 1)
                    {
                        return new RedirectResult(model.RedirectUrl);
                    }
                    model.Organizations = _loginViewModelBuilder.GetOrganizations(organizations);
                    return View(nameof(SelectOrganization), model);
                }
                model.ErrorMessage = "login.failed".AsWebSiteString();
            }
            catch (ChangePasswordException)
            {
                return View(nameof(ChangePassword), model);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(LoginViewModel loginViewModel)
        {
            if (string.IsNullOrWhiteSpace(loginViewModel.LoginForm.UserName) || string.IsNullOrWhiteSpace(loginViewModel.LoginForm.Password))
            {
                return RedirectToAction(nameof(Login));
            }

            var model = _loginViewModelBuilder.Build(loginViewModel);
            model.RedirectUrl = loginViewModel.RedirectUrl;

            if (!_myPagesViewModelService.IsValidPasswordForm(_modelState, model.ChangePasswordForm,
                model.LoginForm.Password))
            {
                return View(model);
            }
            
            var loginSuccessfull = _loginService.Login(model.LoginForm.UserName, model.LoginForm.Password, model.ChangePasswordForm.Password, out var token);
            if (!loginSuccessfull)
            {
                return View(model);
            }
            var person = _loginService.GetUser(model.LoginForm.UserName);
            if (!_loginService.IsBusinessCustomer(person, out var organizations))
            {
                return new RedirectResult(model.RedirectUrl);
            }
                    
            if (organizations.Count <= 1)
            {
                return new RedirectResult(model.RedirectUrl);
            }
            model.Organizations = _loginViewModelBuilder.GetOrganizations(organizations);
            return View(nameof(SelectOrganization), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SelectOrganization(LoginViewModel loginViewModel)
        {
            PersonStorage.CurrentSelectedOrganization = _organizationService.Get(loginViewModel.SelectedOrganization);
            if (PersonStorage.CurrentSelectedOrganization != null)
            {
                return new RedirectResult(loginViewModel.RedirectUrl);
            }

            _loginService.Logout();
            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        public virtual ActionResult ForgotPassword()
        {
            var model = _forgotPasswordViewModelBuilder.Build();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult ForgotPassword(ForgotPasswordViewModel forgotPasswordViewModel)
        {
            var model = _forgotPasswordViewModelBuilder.Build(forgotPasswordViewModel.ForgotPasswordForm);

            if (_loginService.IsValidForgotPasswordForm(_modelState, model.ForgotPasswordForm))
            {
                var user = _loginService.GetUser(model.ForgotPasswordForm.Email?.ToLower());
                if (user == null)
                {
                    model.ErrorMessage = "login.usernotfound".AsWebSiteString();
                }
                else
                {
                    if (!string.IsNullOrEmpty(user.Email))
                    {
                        if (_loginService.ChangePassword(user, false, true, model.ChannelSystemId, _securityToken))
                        {
                            model.Message = "login.passwordsent".AsWebSiteString();
                        }
                        else
                        {
                            model.ErrorMessage = "login.passwordcouldnotbesent".AsWebSiteString();
                        }
                    }
                    else
                    {
                        model.ErrorMessage = "login.passwordcouldnotbesent".AsWebSiteString();
                    }
                }
            }

            return View(model);
        }

        [HttpGet]
        public RedirectResult Logout(string redirectUrl)
        {
            _loginService.Logout();

            if (string.IsNullOrWhiteSpace(redirectUrl))
            {
                redirectUrl = "~/";
            }
            return new RedirectResult(redirectUrl);
        }
    }
}

Src/Litium.Accelerator.Mvc/Views/Login/ChangePassword.cshtml
@using Litium.Web.Mvc;
@using Litium.Studio.Extenssions;
@model Litium.Accelerator.ViewModels.Login.LoginViewModel

<div class="full-height">
    <div class="form__container">
        @using (Html.BeginForm("ChangePassword", "Login"))
        {
            @Html.AntiForgeryToken()
            <fieldset class="form">
                <div>
                    @Html.HiddenFor(x => x.RedirectUrl)
                    @Html.HiddenFor(x => x.LoginForm.UserName)
                    @Html.HiddenFor(x => x.LoginForm.Password)
                    @Html.LabelFor(m => m.ChangePasswordForm.Password, "changepassword.newpassword".AsWebSiteString(), new { @class = "form__label" })
                    @Html.PasswordFor(m => m.ChangePasswordForm.Password, new { @class = "form__input", @autocomplete = "new-password" })
                    @Html.ValidationMessageFor(m => m.ChangePasswordForm.Password, string.Empty, new { @class = "form__validator--error" })
                </div>
                <div>
                    @Html.LabelFor(m => m.ChangePasswordForm.ConfirmPassword, "changepassword.confirmpassword".AsWebSiteString(), new { @class = "form__label" })
                    @Html.PasswordFor(m => m.ChangePasswordForm.ConfirmPassword, new { @class = "form__input", @autocomplete = "new-password" })
                    @Html.ValidationMessageFor(m => m.ChangePasswordForm.ConfirmPassword, string.Empty, new { @class = "form__validator--error" })
                </div>
                <div>
                    <input type="submit" class="form__button form__button--expand" value="@Html.WebSiteString("login.changepassword")" />
                </div>
            </fieldset>
        }
    </div>
</div>

Src/Litium.Accelerator.Mvc/Views/Login/ForgotPassword.cshtml
@using Litium.Studio.Extenssions;
@using Litium.Web.Mvc;
@model Litium.Accelerator.ViewModels.Login.ForgotPasswordViewModel

<div class="full-height">
    <div class="form__container">
        @if (!User.Identity.IsAuthenticated)
        {
            <h1>@Model.Title</h1>
            if (!string.IsNullOrWhiteSpace(Model.Message))
            {
                <div>
                    <div data-alert class="alert alert-box success">
                        @Model.Message
                    </div>
                    @if (Model.LoginLink != null)
                    {
                        <div>
                            <a href="@Model.LoginLink.Href">@Html.WebSiteString("forgotpassword.clicktologin")</a>
                        </div>
                    }
                </div>
            }
            else
            {
                if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
                {
                    <div>
                        <div class="form__validator">
                            <small class="form__validator--error">@Model.ErrorMessage</small>
                        </div>
                    </div>
                }

                using (Html.BeginForm("ForgotPassword", "Login"))
                {
                    @Html.AntiForgeryToken()
                    <fieldset class="form">
                        <div>
                            @Html.LabelFor(x => x.ForgotPasswordForm.Email, "forgotpassword.email".AsWebSiteString(), new { @class = "form__label" })
                            @Html.TextBoxFor(x => x.ForgotPasswordForm.Email, new { @class = "form__input", @autocomplete = "email" })
                            @Html.ValidationMessageFor(x => x.ForgotPasswordForm.Email, string.Empty, new { @class = "form__validator--error" })
                        </div>
                        <input type="submit" class="form__button form__button--expand" value="@Html.WebSiteString("forgotpassword.sendnewpassword")" />
                        @if (Model.LoginLink != null)
                        {
                            <div>
                                <a href="@Model.LoginLink.Href">@Html.WebSiteString("forgotpassword.backtologinpage")</a>
                            </div>
                        }
                    </fieldset>
                }
            }
        }
        else
        {
            <fieldset class="form">
                <p>@(string.Format("forgotpassword.alreadylogin".AsWebSiteString(), User.Identity.Name))</p>
                @Html.ActionLink("forgotpassword.logout".AsWebSiteString(), "Logout", "Login", null, new { @class = "button submit small" })
            </fieldset>
        }

    </div>
</div>

Src/Litium.Accelerator.Mvc/Views/Login/Login.cshtml
@using Litium.Web.Mvc;
@using Litium.Studio.Extenssions;
@model Litium.Accelerator.ViewModels.Login.LoginViewModel

<div class="full-height">
    <div class="form__container">
        @if (!User.Identity.IsAuthenticated)
        {
            <h1>@Model.Title</h1>
            if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
            {
                <div class="form__validator">
                    <small class="form__validator--error">@Model.ErrorMessage</small>
                </div>
            }
            using (Html.BeginForm("Login", "Login"))
            {
                @Html.AntiForgeryToken()
                <fieldset class="form">
                    <div>
                        @Html.HiddenFor(x => x.RedirectUrl)
                        @Html.LabelFor(x => x.LoginForm.UserName, "login.username".AsWebSiteString(), new { @class = "form__label" })
                        @Html.TextBoxFor(x => x.LoginForm.UserName, new { @class = "form__input", @autocomplete = "username" })
                        @Html.ValidationMessageFor(x => x.LoginForm.UserName, string.Empty, new { @class = "form__validator--error" })
                    </div>
                    <div>
                        @Html.LabelFor(x => x.LoginForm.Password, "login.password".AsWebSiteString(), new { @class = "form__label" })
                        @Html.PasswordFor(x => x.LoginForm.Password, new { @class = "form__input", @autocomplete = "current-password" })
                        @Html.ValidationMessageFor(x => x.LoginForm.Password, string.Empty, new { @class = "form__validator--error" })
                    </div>
                    <input type="submit" class="form__button form__button--expand" value="@Html.WebSiteString("login.loginbuttontext")" />
                    @if (Model.ForgottenPasswordLink != null && !string.IsNullOrEmpty(Model.ForgottenPasswordLink.Href))
                    {
                        <a href="@Model.ForgottenPasswordLink.Href">@Html.WebSiteString("login.clicktogotoforgotpasswordpage")</a>
                    }
                </fieldset>
            }
        }
        else
        {
            <fieldset class="form">
                <p>@(string.Format("login.alreadylogin".AsWebSiteString(), User.Identity.Name))</p>
                @Html.ActionLink("login.logout".AsWebSiteString(), "Logout", "Login", null, new { @class = "button submit small" })
            </fieldset>
        }
    </div>
</div>

Src/Litium.Accelerator.Mvc/Views/Login/SelectOrganization.cshtml
@using Litium.Web.Mvc;
@using Litium.Studio.Extenssions;
@model Litium.Accelerator.ViewModels.Login.LoginViewModel

<div class="full-height">
    <div class="form__container">
        @using (Html.BeginForm("SelectOrganization", "Login"))
        {
            @Html.AntiForgeryToken()
            <fieldset class="form">
                <div>
                    @Html.HiddenFor(x => x.RedirectUrl)
                    @Html.LabelFor(x => x.SelectedOrganization, "login.selectorganization".AsWebSiteString(), new { @class = "form__label" })
                    @Html.DropDownListFor(x => x.SelectedOrganization, Model.Organizations, new { @class = "form__input" })
                </div>
                <input type="submit" class="form__button form__button--expand" value="@Html.WebSiteString("general.select")" />
            </fieldset>
        }
    </div>
</div>