Src/Litium.Accelerator.Mvc/Controllers/Api/NavigationController.cs
using System.Web.Http;
using Litium.Accelerator.Builders.Framework;

namespace Litium.Accelerator.Mvc.Controllers.Api
{
    public class NavigationController : ApiControllerBase
    {
        private readonly NavigationViewModelBuilder _navigationViewModelBuilder;

        public NavigationController(NavigationViewModelBuilder navigationViewModelBuilder)
        {
            _navigationViewModelBuilder = navigationViewModelBuilder;
        }

        /// <summary>
        /// Get navigation menu
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IHttpActionResult Get()
        {
            return Ok(_navigationViewModelBuilder.Build());
        }
    }
}

Src/Litium.Accelerator.Mvc/Controllers/Brand/BrandController.cs
using Litium.Web.Models.Websites;
using System.Web.Mvc;
using Litium.Accelerator.Builders.Brand;

namespace Litium.Accelerator.Mvc.Controllers.Brand
{
    public class BrandController : ControllerBase
    {
        private readonly BrandViewModelBuilder _brandViewModelBuilder;
        private readonly BrandListViewModelBuilder _brandListViewModelBuilder;
        
        public BrandController(BrandViewModelBuilder brandViewModelBuilder, BrandListViewModelBuilder brandListViewModelBuilder)
        {
            _brandViewModelBuilder = brandViewModelBuilder;
            _brandListViewModelBuilder = brandListViewModelBuilder;
        }

        [HttpGet]
        public ActionResult Index(PageModel currentPageModel)
        {
            var model = _brandViewModelBuilder.Build(currentPageModel);
            return View(model);
        }

        [HttpGet]
        public ActionResult List(PageModel currentPageModel)
        {
            var model = _brandListViewModelBuilder.Build(currentPageModel);
            return View(model);
        }
    }
}

Src/Litium.Accelerator.Mvc/Views/Brand/Index.cshtml
@using Litium.Studio.Extenssions;
@using Litium.Accelerator.Constants;
@model Litium.Accelerator.ViewModels.Brand.BrandViewModel

<div id="search-result" class="row">
    <div class="small-12 columns">
        @if (Model.Blocks.Any() && !Model.ContainsFilter)
        {
            <h1 class="structural">@Html.DisplayFor(x => x.Title)</h1>
            @Html.BlockContainer(Model.Blocks, BlockContainerNameConstant.Header)
        }

        @if (Model.ShowRegularHeader)
        {
            <div class="product__group-header">
                <h1>@Model.Title</h1>
                @Html.ImageFor(x => x.Image, htmlAttributes: new { @class = "product__group-image" })
                @Model.Text
            </div>
        }
        @if (Model.Pagination.TotalCount > 1 || Model.ContainsFilter)
        {
            <div id="facetedSearchCompact" class="compact-filter"></div>
        }
        @if (Model.ShowFilterHeader)
        {
            <h1>@Html.DisplayFor(x => x.Title) <span>(@Model.Pagination.TotalCount)</span></h1>
        }
        <div>
            @if (Model.Pagination != null && Model.Pagination.TotalCount > 0)
            {
                if (Model.Pagination.TotalCount > 1 || Model.ContainsFilter)
                {
                    Html.RenderAction("CategoryFiltering", "Navigation", new { TotalHits = Model.Pagination.TotalCount });
                }
                if (Model.Products != null && Model.Products.Any())
                {
                    <div class="product-list">
                        <ul class="row product-list">
                            @foreach (var product in Model.Products)
                            {
                                <li class="product-list__item columns small-6 medium-4 large-3">@Html.DisplayFor(x => product, new { maxWidth = 371 })</li>
                            }
                        </ul>
                    </div>
                }
            }
            @Html.DisplayFor(x => x.Pagination)
        </div>
    </div>
</div>

Src/Litium.Accelerator.Mvc/Views/Brand/List.cshtml
@model Litium.Accelerator.ViewModels.Brand.BrandListViewModel
<div class="brands-list__container">
    <h1 class="brands-list__header">@Model.TitleFilterSelector</h1>
    @foreach (var row in Model.Nodes)
    {
        <ul class="brands-list row expanded">
            @foreach (var letterGroup in row)
            {
                <li class="small-12 medium-@(12 / Model.MaxColumns) columns">
                    <div class="brands-list__group">
                        <span class="brands-list__group-letter">@letterGroup.Value.Name</span>
                        <ul class="brands-list__sublist">
                            @foreach (var brand in letterGroup)
                            {
                                <li class="brands-list__sublist-item"><a href="@brand.Value.Url">@brand.Value.Name</a> <span>(@brand.Value.ExtraInfo)</span></li>
                            }
                        </ul>
                    </div>
                </li>
            }
        </ul>
    }
</div>